import express from "express";
import { generatePdf } from "../controllers/pdf-source-form-data.controller";
import {
  validatePdfFormDataRequest,
} from "../middleware/validate-pdf-request";

const pdfRouter = express.Router();

/**
 * @swagger
 * /api/pdf/generate:
 *   post:
 *     tags:
 *       - Pdf generation
 *     summary: Generate a PDF from a source and provided data in multipart/form-data of request
 *     description: |
 *       This endpoint generates a PDF based on:
 *       - the **source** (the Lunatic questionnaire generated by Eno) provided in requestBody.
 *       - the **interrogation** provided in the request body (wiht **data** -> LunaticData)
 *
 *       The PDF is returned as a binary file with the header `Content-Disposition: attachment; filename=export.pdf`.
 *     requestBody:
 *      required: true
 *      content:
 *        application/json:
 *          schema:
 *            type: object
 *            required:
 *              - source
 *              - interrogation
 *            properties:
 *              source:
 *                type: object
 *                description: Lunatic Source i.e  source requis pour la génération
 *              interrogation:
 *                type: object
 *                required:
 *                  - data
 *                properties:
 *                  interrogationId:
 *                    type: string
 *                    format: uuid
 *                    description: string (uuid format) from collect information system
 *                  usualSurveyUnitId:
 *                    type: string
 *                    description: string corresponding to business ID (SIRET/SIREN number)
 *                    example: INSEE (Siret 98767543210)
 *                  collectionInstrumentId:
 *                    type: string
 *                    description: the id of collection instrument i.e ID of source use inside collect information system (can not be the same as source.id)
 *                    example: EAP2026X00
 *                  validationDate:
 *                    type: string
 *                    format: date-time
 *                    description: the date of validation of the questionnaire (format iso, ex 2026-02-03T12:20:29.275709359Z)
 *                  data:
 *                    type: object
 *                    description: Lunatic data
 *     responses:
 *       '200':
 *         description: Returns a PDF file
 *         content:
 *           application/pdf:
 *             schema:
 *               type: string
 *               format: binary
 *       '400':
 *         description: Missing or invalid `source` parameter
 *       '500':
 *         description: Internal server error during PDF generation
 */
pdfRouter.post("/generate", validatePdfFormDataRequest, generatePdf);
export default pdfRouter;
