import express from "express";
import { generatePdf as generatePdfWithUri } from "../controllers/pdf-source-uri.controller";
import { generatePdf } from "../controllers/pdf-source-form-data.controller";
import {
  validatePdfFormDataRequest,
  validatePdfUriRequest,
} from "../middleware/validate-pdf-request";

const pdfRouter = express.Router();

/**
 * @swagger
 * /api/pdf/generate-from-source:
 *   post:
 *     tags:
 *       - Pdf generation
 *     summary: Generate a PDF from a source as URI and provided data in body of request
 *     description: |
 *       This endpoint generates a PDF based on:
 *       - a **source** (the Lunatic questionnaire URL) provided as a query parameter. (ex URI from Registry-Api )
 *       - a Lunatic **data** provided in the request body (JSON format, can be object included the key _data_ that includes Lunatic Data, or LunaticData directly).
 *
 *       The PDF is returned as a binary file with the header `Content-Disposition: attachment; filename=export.pdf`.
 *     parameters:
 *       - in: query
 *         name: source
 *         required: true
 *         description: URL of the Lunatic questionnaire (URI format)
 *         schema:
 *           type: string
 *           format: uri
 *     requestBody:
 *       required: true
 *       description: Data used to populate the PDF
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             additionalProperties: true
 *             description: |
 *               - `data` (object): Questionnaire data
 *     responses:
 *       '200':
 *         description: Returns a PDF file
 *         content:
 *           application/pdf:
 *             schema:
 *               type: string
 *               format: binary
 *       '400':
 *         description: Missing or invalid `source` parameter
 *       '500':
 *         description: Internal server error during PDF generation
 */
pdfRouter.post(
  "/generate-from-source",
  validatePdfUriRequest,
  generatePdfWithUri
);

/**
 * @swagger
 * /api/pdf/generate:
 *   post:
 *     tags:
 *       - Pdf generation
 *     summary: Generate a PDF from a source and provided data in multipart/form-data of request
 *     description: |
 *       This endpoint generates a PDF based on:
 *       - the **source** (the Lunatic questionnaire generated by Eno) provided in requestBody.
 *       - the **interrogation** provided in the request body (wiht **data** -> LunaticData)
 *
 *       The PDF is returned as a binary file with the header `Content-Disposition: attachment; filename=export.pdf`.
 *     requestBody:
 *      required: true
 *      content:
 *        application/json:
 *          schema:
 *            type: object
 *            required:
 *              - source
 *              - interrogation
 *            properties:
 *              source:
 *                type: object
 *                description: Lunatic Source i.e  source requis pour la génération
 *              interrogation:
 *                type: object
 *                required:
 *                  - data
 *                properties:
 *                  interrogationId:
 *                    type: string
 *                    format: uuid
 *                    description: string (uuid format) from collect information system
 *                  usualSurveyUnitId:
 *                    type: string
 *                    description: string corresponding to business ID (SIRET/SIREN number)
 *                    example: INSEE (Siret 98767543210)
 *                  collectionInstrumentId:
 *                    type: string
 *                    description: the id of collection instrument i.e ID of source use inside collect information system (can not be the same as source.id)
 *                    example: EAP2026X00
 *                  validationDate:
 *                    type: string
 *                    format: date-time
 *                    description: the date of validation of the questionnaire (format iso, ex 2026-02-03T12:20:29.275709359Z)
 *                  data:
 *                    type: object
 *                    description: Lunatic data
 *     responses:
 *       '200':
 *         description: Returns a PDF file
 *         content:
 *           application/pdf:
 *             schema:
 *               type: string
 *               format: binary
 *       '400':
 *         description: Missing or invalid `source` parameter
 *       '500':
 *         description: Internal server error during PDF generation
 */
pdfRouter.post("/generate", validatePdfFormDataRequest, generatePdf);
export default pdfRouter;
