import type {
  LunaticComponentDefinition,
  LunaticData,
  LunaticSource,
} from "@inseefr/lunatic";
import { Request } from "express";
import type { ReactNode } from "react";

export type LunaticComponentProps<T extends string> = {
  interpret: (expr: VTLExpression | string | undefined) => ReactNode;
} & LunaticComponentDefinition<T>;

export type VTLExpression = {
  value: string;
  bindingDependencies?: string[];
  type: "VTL" | "VTL|MD" | "TXT";
};

export interface PdfRequestFromUri extends Request {
  query: {
    source?: string;
  };
  body: unknown;
}

export interface PdfRequestFromBody extends Request {
  body: {
    /**
     * Questionnaire model generated by Eno in Lunatic-Model format
     */
    source: LunaticSource;
    interrogation: {
      /**
       * string (uuid format) from collect information system
       */
      interrogationId: string;
      /**
       * string corresponding to business ID (SIRET/SIREN number)
       */
      usualSurveyUnitId: string;
      /**
       * the id of collection instrument i.e ID of source use inside collect information system (can not be the same as source.id)
       */
      collectionInstrumentId: string;
      /**
       * the date of validation of the questionnaire (format iso, ex 2026-02-03T12:20:29.275709359Z)
       */
      validationDate: string;
      /**
       * LunaticData, lunatic format
       */
      data: LunaticData;
    };
  };
}
